source "./scripts/replace_image.sh"
format="./player_introduction/player_introduction_%02d.png"

cp -f $(printf $format $player01) "streaming/player_introduction_1_1_1.png"
cp -f $(printf $format $player02) "streaming/player_introduction_1_1_2.png"
cp -f $(printf $format $player03) "streaming/player_introduction_1_1_3.png"
cp -f $(printf $format $player04) "streaming/player_introduction_1_1_4.png"
cp -f $(printf $format $player05) "streaming/player_introduction_1_2_1.png"
cp -f $(printf $format $player06) "streaming/player_introduction_1_2_2.png"
cp -f $(printf $format $player07) "streaming/player_introduction_1_2_3.png"
cp -f $(printf $format $player08) "streaming/player_introduction_1_2_4.png"

cp -f $(printf $format $player09) "streaming/player_introduction_2_1_1.png"
cp -f $(printf $format $player10) "streaming/player_introduction_2_1_2.png"
cp -f $(printf $format $player11) "streaming/player_introduction_2_1_3.png"
cp -f $(printf $format $player12) "streaming/player_introduction_2_1_4.png"
cp -f $(printf $format $player13) "streaming/player_introduction_2_2_1.png"
cp -f $(printf $format $player14) "streaming/player_introduction_2_2_2.png"
cp -f $(printf $format $player15) "streaming/player_introduction_2_2_3.png"
cp -f $(printf $format $player16) "streaming/player_introduction_2_2_4.png"