name: Update Match Announce Develop
on: 
  workflow_dispatch:
    inputs:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: 'develop'
      - name: Create Branch
        run: |
          git checkout -B pr_test_${{ github.run_number }}
      - name: Download Image
        run: |
          curl -L 'https://script.google.com/macros/s/AKfycbyDVgKZXgC9jtIrqe2qz-FStb-F1CW6c3PaIVVSm_LsiZYRb8_gCmZhyAYJs51ldPXu/exec' | base64 --decode > streaming/match_announce_1_1.png
      - name: Count changes
        id: count_changes
        run: |
          git add streaming
          echo "count=$(git diff --cached --name-only | wc -l)" >> $GITHUB_OUTPUT
      - name: Commit & Push
        if: steps.count_changes.outputs.count > 0
        run: |
          git config user.email "y.tama.league@gmail.com"
          git config user.name "y-tama-league"
          git add streaming/match_announce_1_1.png
          git commit -m "image generated (https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          git push origin HEAD
      - name: Create PR
        if: steps.count_changes.outputs.count > 0
        id: create_pr
        run: |
          echo "pr_url=$(gh pr create \
          -B develop \
          -H pr_test_${{ github.run_number }} \
          -t '配信用画像更新' \
          -b 'generated by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
          -a ${{ github.actor }})" \
          >> $GITHUB_OUTPUT
      - name: Merge PR
        if: steps.count_changes.outputs.count > 0
        run: |
          gh pr merge pr_test_${{ github.run_number }} -d -s
      - name: Discord Notification
        if: steps.count_changes.outputs.count > 0
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: "https://discord.com/api/webhooks/1185504716659101767/OZUmuAWBMGq-vKqBf6tCyd1DIhWOpY4NGPmalwIlVg493zTialHtAFyb3vp8RglkIp4i"
          content: "画像更新PRをマージしました ${{ steps.create_pr.outputs.pr_url }}"
      - uses: sarisia/actions-status-discord@v1.13.0
        if: failure()
        with:
          webhook: "https://discord.com/api/webhooks/1185504662124765244/e6jyJIvgi0Zq36BUuaoX2wHZaXoboIMEA0sxEjh3wiZ14qo7duZ_gxrL8_1bNHhOuWxa"