name: Update Match Announce Production
on: 
  workflow_dispatch:
    inputs:
      players:
        descripts: array of player-id & team-id
        required: true
jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Create Branch
        run: |
          git checkout -B update_assets_${{ github.run_number }}
      - name: Download Image
        run: |
          mkdir streaming || true
          curl -L "${{ secrets.ASSET_GENERATION_API_ENDPOINT }}?api=downloadImage&page=0" | base64 --decode > streaming/match_announce_1_1.png
          curl -L "${{ secrets.ASSET_GENERATION_API_ENDPOINT }}?api=downloadImage&page=1" | base64 --decode > streaming/match_announce_1_2.png
          curl -L "${{ secrets.ASSET_GENERATION_API_ENDPOINT }}?api=downloadImage&page=2" | base64 --decode > streaming/match_announce_1_3.png
          curl -L "${{ secrets.ASSET_GENERATION_API_ENDPOINT }}?api=downloadImage&page=3" | base64 --decode > streaming/match_announce_2_1.png
          curl -L "${{ secrets.ASSET_GENERATION_API_ENDPOINT }}?api=downloadImage&page=4" | base64 --decode > streaming/match_announce_2_2.png
          curl -L "${{ secrets.ASSET_GENERATION_API_ENDPOINT }}?api=downloadImage&page=5" | base64 --decode > streaming/match_announce_2_3.png
      - name: Replace Image
        run: |
          cp_image() {
              match=$1; table=$2; seat=$3
              tmp=(${4//:/ })
              player=${tmp[0]};
              team=${tmp[1]}

              cp "latest/team_logo/team_logo_${team}_1000x.png" "streaming/team_logo_${match}_${table}_${seat}.png" || true
              cp "offcial_game/battle_player_info/battle_player_info_${player}.png" "streaming/battle_player_info_${match}_${table}_${seat}.png" || true
              cp "offcial_game/player_introduction/background/player_introduction_background_${team}.png" "streaming/player_introduction_background_${match}_${table}_${seat}.png" || true
              cp "offcial_game/player_introduction/illust/player_introduction_illust_${player}.png" "streaming/player_introduction_illust_${match}_${table}_${seat}.png" || true
              cp "offcial_game/player_introduction/name/player_introduction_name_${player}.png" "streaming/player_introduction_name_${match}_${table}_${seat}.png" || true
              cp "offcial_game/player_introduction/name_frvont/player_introduction_name_front_${player}.png" "streaming/player_introduction_name_front_${match}_${table}_${seat}.png" || true
              cp "offcial_game/interview/interview_${player}.jpg" "streaming/interview_${match}_${table}_${seat}.jpg" || true
              cp "offcial_game/interview/player_name_plate_${player}.jpg" "streaming/player_name_plate_${match}_${table}_${seat}.jpg" || true
          }

          players=${{ github.event.inputs.players }}
          players=(${players//,/ })

          echo ${players[@]}

          cp_image 01 01 01 ${players[0]}
          cp_image 01 01 02 ${players[1]}
          cp_image 01 01 03 ${players[2]}
          cp_image 01 01 04 ${players[3]}

          cp_image 01 02 01 ${players[4]}
          cp_image 01 02 02 ${players[5]}
          cp_image 01 02 03 ${players[6]}
          cp_image 01 02 04 ${players[7]}

          cp_image 01 03 01 ${players[8]}
          cp_image 01 03 02 ${players[9]}
          cp_image 01 03 03 ${players[10]}
          cp_image 01 03 04 ${players[11]}

          cp_image 02 01 01 ${players[12]}
          cp_image 02 01 02 ${players[13]}
          cp_image 02 01 03 ${players[14]}
          cp_image 02 01 04 ${players[15]}

          cp_image 02 02 01 ${players[16]}
          cp_image 02 02 02 ${players[17]}
          cp_image 02 02 03 ${players[18]}
          cp_image 02 02 04 ${players[19]}

          cp_image 02 03 01 ${players[20]}
          cp_image 02 03 02 ${players[21]}
          cp_image 02 03 03 ${players[22]}
          cp_image 02 03 04 ${players[23]}
      - name: Count changes
        id: count_changes
        run: |
          git add streaming
          echo "count=$(git diff --cached --name-only | wc -l)" >> $GITHUB_OUTPUT
      - name: Commit & Push
        if: steps.count_changes.outputs.count > 0
        run: |
          git config user.email "y.tama.league@gmail.com"
          git config user.name "y-tama-league"
          git commit -m "image generated (https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          git push origin HEAD
      - name: Create PR
        if: steps.count_changes.outputs.count > 0
        id: create_pr
        run: |
          echo "pr_url=$(gh pr create \
          -B main \
          -H update_assets_${{ github.run_number }} \
          -t '配信用画像更新' \
          -b 'generated by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
          -a ${{ github.actor }})" \
          >> $GITHUB_OUTPUT
      - name: Merge PR
        if: steps.count_changes.outputs.count > 0
        run: |
          gh pr merge update_assets_${{ github.run_number }} -d -s
      - name: Discord Notification
        if: steps.count_changes.outputs.count > 0
        uses: sarisia/actions-status-discord@v1.13.0
        with:
          webhook: ${{ secrets.NOTIFICATION_TARGET }}
          title: 画像更新PRをマージしました
          description: ${{ steps.create_pr.outputs.pr_url }}
          nodetail: true
          notimestamp: true
