name: Update Match Announce Develop
on: 
  workflow_dispatch:
    inputs:
      players:
        descripts: array of paleyr id
        required: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: 'develop'
      - name: Create Branch
        run: |
          git checkout -B pr_test_${{ github.run_number }}
      - name: Download Image
        run: |
          curl -L 'https://script.google.com/macros/s/AKfycbx8uGR7utFSeYi1AO8r9dGKSFsWgKK4DYh0nUFZCLfN6Vr_s5qtNftmnx1c21kkgcwjPw/exec?api=downloadImage&page=0' | base64 --decode > streaming/match_announce_1_1.png
          curl -L 'https://script.google.com/macros/s/AKfycbx8uGR7utFSeYi1AO8r9dGKSFsWgKK4DYh0nUFZCLfN6Vr_s5qtNftmnx1c21kkgcwjPw/exec?api=downloadImage&page=1' | base64 --decode > streaming/match_announce_1_2.png
          curl -L 'https://script.google.com/macros/s/AKfycbx8uGR7utFSeYi1AO8r9dGKSFsWgKK4DYh0nUFZCLfN6Vr_s5qtNftmnx1c21kkgcwjPw/exec?api=downloadImage&page=2' | base64 --decode > streaming/match_announce_1_3.png
          curl -L 'https://script.google.com/macros/s/AKfycbx8uGR7utFSeYi1AO8r9dGKSFsWgKK4DYh0nUFZCLfN6Vr_s5qtNftmnx1c21kkgcwjPw/exec?api=downloadImage&page=3' | base64 --decode > streaming/match_announce_2_1.png
          curl -L 'https://script.google.com/macros/s/AKfycbx8uGR7utFSeYi1AO8r9dGKSFsWgKK4DYh0nUFZCLfN6Vr_s5qtNftmnx1c21kkgcwjPw/exec?api=downloadImage&page=4' | base64 --decode > streaming/match_announce_2_2.png
          curl -L 'https://script.google.com/macros/s/AKfycbx8uGR7utFSeYi1AO8r9dGKSFsWgKK4DYh0nUFZCLfN6Vr_s5qtNftmnx1c21kkgcwjPw/exec?api=downloadImage&page=5' | base64 --decode > streaming/match_announce_2_3.png
      - name: Replace Image
        run: |
          cp_image() {
              match=$1; table=$2; seat=$3
              tmp=(${4//:/ })
              player=${tmp[0]};
              team=${tmp[1]}

              cp "season2/battle_player_info/battle_player_info_${player}.png" "streaming/battle_player_info_${match}_${table}_${seat}.png"
              cp "season2/player_introduction/background/player_introduction_background_${team}.png" "streaming/player_introduction_background_${match}_${table}_${seat}.png"
              cp "season2/player_introduction/illust/player_introduction_illust_${player}.png" "streaming/player_introduction_illust_${match}_${table}_${seat}.png"
              cp "season2/player_introduction/name/player_introduction_name_${player}.png" "streaming/player_introduction_name_${match}_${table}_${seat}.png"
          }

          players=(${${{ github.event.inputs.players }}//,/ })

          cp_image 01 01 01 ${players[0]}
          cp_image 01 01 02 ${players[1]}
          cp_image 01 01 03 ${players[2]}
          cp_image 01 02 01 ${players[3]}
          cp_image 01 02 02 ${players[4]}
          cp_image 01 02 03 ${players[5]}

          cp_image 02 01 01 ${players[6]}
          cp_image 02 01 02 ${players[7]}
          cp_image 02 01 03 ${players[8]}
          cp_image 02 02 01 ${players[9]}
          cp_image 02 02 02 ${players[10]}
          cp_image 02 02 03 ${players[11]}

      - name: Count changes
        id: count_changes
        run: |
          git add streaming
          echo "count=$(git diff --cached --name-only | wc -l)" >> $GITHUB_OUTPUT
      - name: Commit & Push
        if: steps.count_changes.outputs.count > 0
        run: |
          git config user.email "y.tama.league@gmail.com"
          git config user.name "y-tama-league"
          git add streaming/match_announce_1_1.png
          git commit -m "image generated (https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          git push origin HEAD
      - name: Create PR
        if: steps.count_changes.outputs.count > 0
        id: create_pr
        run: |
          echo "pr_url=$(gh pr create \
          -B develop \
          -H pr_test_${{ github.run_number }} \
          -t '配信用画像更新' \
          -b 'generated by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
          -a ${{ github.actor }})" \
          >> $GITHUB_OUTPUT
      - name: Merge PR
        if: steps.count_changes.outputs.count > 0
        run: |
          gh pr merge pr_test_${{ github.run_number }} -d -s
      - name: Discord Notification
        if: steps.count_changes.outputs.count > 0
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: "https://discord.com/api/webhooks/1185504716659101767/OZUmuAWBMGq-vKqBf6tCyd1DIhWOpY4NGPmalwIlVg493zTialHtAFyb3vp8RglkIp4i"
          content: "画像更新PRをマージしました ${{ steps.create_pr.outputs.pr_url }}"
      - uses: sarisia/actions-status-discord@v1.13.0
        if: failure()
        with:
          webhook: "https://discord.com/api/webhooks/1185504662124765244/e6jyJIvgi0Zq36BUuaoX2wHZaXoboIMEA0sxEjh3wiZ14qo7duZ_gxrL8_1bNHhOuWxa"